root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server"
  bin = "./tmp/main"
  include_ext = ["go", "toml"]
  exclude_dir = ["tmp", "vendor", "db"]
  delay = 1000
  kill_delay = 500
  rerun = false
  rerun_delay = 500

[log]
  time = true
  color = true

[color]
  main     = "magenta"
  watcher  = "cyan"
  build    = "yellow"
  runner   = "green"

[misc]
  clean_on_exit = true
