// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: babysitter_profiles.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const approveBabysitter = `-- name: ApproveBabysitter :one
UPDATE babysitter_profiles
SET is_approved = TRUE, updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, location, national_id_url, lci_letter_url, cv_url, profile_picture_url, languages, days_per_week, hours_per_day, rate_type, rate_amount, payment_method, is_approved, created_at, updated_at
`

func (q *Queries) ApproveBabysitter(ctx context.Context, userID uuid.UUID) (BabysitterProfile, error) {
	row := q.db.QueryRowContext(ctx, approveBabysitter, userID)
	var i BabysitterProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Location,
		&i.NationalIDUrl,
		&i.LciLetterUrl,
		&i.CvUrl,
		&i.ProfilePictureUrl,
		pq.Array(&i.Languages),
		&i.DaysPerWeek,
		&i.HoursPerDay,
		&i.RateType,
		&i.RateAmount,
		&i.PaymentMethod,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBabysitterProfile = `-- name: CreateBabysitterProfile :one
INSERT INTO babysitter_profiles (user_id, location, national_id_url, lci_letter_url, cv_url, profile_picture_url, languages, days_per_week, hours_per_day, rate_type, rate_amount, payment_method)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, user_id, location, national_id_url, lci_letter_url, cv_url, profile_picture_url, languages, days_per_week, hours_per_day, rate_type, rate_amount, payment_method, is_approved, created_at, updated_at
`

type CreateBabysitterProfileParams struct {
	UserID            uuid.UUID
	Location          sql.NullString
	NationalIDUrl     sql.NullString
	LciLetterUrl      sql.NullString
	CvUrl             sql.NullString
	ProfilePictureUrl sql.NullString
	Languages         []string
	DaysPerWeek       sql.NullInt32
	HoursPerDay       sql.NullInt32
	RateType          NullRateType
	RateAmount        sql.NullString
	PaymentMethod     sql.NullString
}

func (q *Queries) CreateBabysitterProfile(ctx context.Context, arg CreateBabysitterProfileParams) (BabysitterProfile, error) {
	row := q.db.QueryRowContext(ctx, createBabysitterProfile,
		arg.UserID,
		arg.Location,
		arg.NationalIDUrl,
		arg.LciLetterUrl,
		arg.CvUrl,
		arg.ProfilePictureUrl,
		pq.Array(arg.Languages),
		arg.DaysPerWeek,
		arg.HoursPerDay,
		arg.RateType,
		arg.RateAmount,
		arg.PaymentMethod,
	)
	var i BabysitterProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Location,
		&i.NationalIDUrl,
		&i.LciLetterUrl,
		&i.CvUrl,
		&i.ProfilePictureUrl,
		pq.Array(&i.Languages),
		&i.DaysPerWeek,
		&i.HoursPerDay,
		&i.RateType,
		&i.RateAmount,
		&i.PaymentMethod,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBabysitterProfileByUserID = `-- name: GetBabysitterProfileByUserID :one
SELECT id, user_id, location, national_id_url, lci_letter_url, cv_url, profile_picture_url, languages, days_per_week, hours_per_day, rate_type, rate_amount, payment_method, is_approved, created_at, updated_at FROM babysitter_profiles
WHERE user_id = $1
`

func (q *Queries) GetBabysitterProfileByUserID(ctx context.Context, userID uuid.UUID) (BabysitterProfile, error) {
	row := q.db.QueryRowContext(ctx, getBabysitterProfileByUserID, userID)
	var i BabysitterProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Location,
		&i.NationalIDUrl,
		&i.LciLetterUrl,
		&i.CvUrl,
		&i.ProfilePictureUrl,
		pq.Array(&i.Languages),
		&i.DaysPerWeek,
		&i.HoursPerDay,
		&i.RateType,
		&i.RateAmount,
		&i.PaymentMethod,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApprovedBabysitters = `-- name: ListApprovedBabysitters :many
SELECT u.id, u.full_name, u.email, u.phone, u.status,
       bp.location, bp.profile_picture_url, bp.languages,
       bp.days_per_week, bp.hours_per_day, bp.rate_type,
       bp.rate_amount, bp.payment_method, bp.is_approved
FROM users u
JOIN babysitter_profiles bp ON u.id = bp.user_id
WHERE u.role = 'babysitter'
  AND u.deleted_at IS NULL
  AND u.status = 'active'
  AND bp.is_approved = TRUE
ORDER BY u.created_at DESC
`

type ListApprovedBabysittersRow struct {
	ID                uuid.UUID
	FullName          string
	Email             string
	Phone             sql.NullString
	Status            UserStatus
	Location          sql.NullString
	ProfilePictureUrl sql.NullString
	Languages         []string
	DaysPerWeek       sql.NullInt32
	HoursPerDay       sql.NullInt32
	RateType          NullRateType
	RateAmount        sql.NullString
	PaymentMethod     sql.NullString
	IsApproved        bool
}

func (q *Queries) ListApprovedBabysitters(ctx context.Context) ([]ListApprovedBabysittersRow, error) {
	rows, err := q.db.QueryContext(ctx, listApprovedBabysitters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApprovedBabysittersRow
	for rows.Next() {
		var i ListApprovedBabysittersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.Status,
			&i.Location,
			&i.ProfilePictureUrl,
			pq.Array(&i.Languages),
			&i.DaysPerWeek,
			&i.HoursPerDay,
			&i.RateType,
			&i.RateAmount,
			&i.PaymentMethod,
			&i.IsApproved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBabysitterProfile = `-- name: UpdateBabysitterProfile :one
UPDATE babysitter_profiles
SET location = $2, languages = $3, days_per_week = $4, hours_per_day = $5,
    rate_type = $6, rate_amount = $7, payment_method = $8,
    profile_picture_url = $9, updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, location, national_id_url, lci_letter_url, cv_url, profile_picture_url, languages, days_per_week, hours_per_day, rate_type, rate_amount, payment_method, is_approved, created_at, updated_at
`

type UpdateBabysitterProfileParams struct {
	UserID            uuid.UUID
	Location          sql.NullString
	Languages         []string
	DaysPerWeek       sql.NullInt32
	HoursPerDay       sql.NullInt32
	RateType          NullRateType
	RateAmount        sql.NullString
	PaymentMethod     sql.NullString
	ProfilePictureUrl sql.NullString
}

func (q *Queries) UpdateBabysitterProfile(ctx context.Context, arg UpdateBabysitterProfileParams) (BabysitterProfile, error) {
	row := q.db.QueryRowContext(ctx, updateBabysitterProfile,
		arg.UserID,
		arg.Location,
		pq.Array(arg.Languages),
		arg.DaysPerWeek,
		arg.HoursPerDay,
		arg.RateType,
		arg.RateAmount,
		arg.PaymentMethod,
		arg.ProfilePictureUrl,
	)
	var i BabysitterProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Location,
		&i.NationalIDUrl,
		&i.LciLetterUrl,
		&i.CvUrl,
		&i.ProfilePictureUrl,
		pq.Array(&i.Languages),
		&i.DaysPerWeek,
		&i.HoursPerDay,
		&i.RateType,
		&i.RateAmount,
		&i.PaymentMethod,
		&i.IsApproved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
