// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: conversations.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (parent_id, babysitter_id, stream_channel_id)
VALUES ($1, $2, $3)
RETURNING id, parent_id, babysitter_id, stream_channel_id, is_locked, created_at, updated_at
`

type CreateConversationParams struct {
	ParentID        uuid.UUID
	BabysitterID    uuid.UUID
	StreamChannelID sql.NullString
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation, arg.ParentID, arg.BabysitterID, arg.StreamChannelID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.BabysitterID,
		&i.StreamChannelID,
		&i.IsLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, parent_id, babysitter_id, stream_channel_id, is_locked, created_at, updated_at FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.BabysitterID,
		&i.StreamChannelID,
		&i.IsLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationByParticipants = `-- name: GetConversationByParticipants :one
SELECT id, parent_id, babysitter_id, stream_channel_id, is_locked, created_at, updated_at FROM conversations
WHERE parent_id = $1 AND babysitter_id = $2
`

type GetConversationByParticipantsParams struct {
	ParentID     uuid.UUID
	BabysitterID uuid.UUID
}

func (q *Queries) GetConversationByParticipants(ctx context.Context, arg GetConversationByParticipantsParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByParticipants, arg.ParentID, arg.BabysitterID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.BabysitterID,
		&i.StreamChannelID,
		&i.IsLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationsForUser = `-- name: ListConversationsForUser :many
SELECT c.id, c.parent_id, c.babysitter_id, c.stream_channel_id, c.is_locked, c.created_at, c.updated_at,
       u.full_name AS other_user_name,
       COALESCE(
           CASE WHEN c.parent_id = $1 THEN bp.profile_picture_url
                ELSE pp.profile_picture_url
           END,
           ''
       ) AS other_user_profile_picture_url
FROM conversations c
JOIN users u ON (
    CASE WHEN c.parent_id = $1 THEN u.id = c.babysitter_id
         ELSE u.id = c.parent_id
    END
)
LEFT JOIN babysitter_profiles bp ON bp.user_id = c.babysitter_id
LEFT JOIN parent_profiles pp ON pp.user_id = c.parent_id
WHERE c.parent_id = $1 OR c.babysitter_id = $1
ORDER BY c.updated_at DESC
`

type ListConversationsForUserRow struct {
	ID                         uuid.UUID
	ParentID                   uuid.UUID
	BabysitterID               uuid.UUID
	StreamChannelID            sql.NullString
	IsLocked                   bool
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	OtherUserName              string
	OtherUserProfilePictureUrl interface{}
}

func (q *Queries) ListConversationsForUser(ctx context.Context, parentID uuid.UUID) ([]ListConversationsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsForUser, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsForUserRow
	for rows.Next() {
		var i ListConversationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.BabysitterID,
			&i.StreamChannelID,
			&i.IsLocked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OtherUserName,
			&i.OtherUserProfilePictureUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConversation = `-- name: LockConversation :exec
UPDATE conversations
SET is_locked = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) LockConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, lockConversation, id)
	return err
}

const lockConversationsByUser = `-- name: LockConversationsByUser :exec
UPDATE conversations
SET is_locked = TRUE, updated_at = NOW()
WHERE babysitter_id = $1 OR parent_id = $1
`

func (q *Queries) LockConversationsByUser(ctx context.Context, babysitterID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, lockConversationsByUser, babysitterID)
	return err
}
