// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: messages.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countUnreadMessagesForUser = `-- name: CountUnreadMessagesForUser :one
SELECT COUNT(*) FROM messages m
JOIN conversations c ON c.id = m.conversation_id
WHERE (c.parent_id = $1 OR c.babysitter_id = $1)
  AND m.sender_id != $1
  AND m.is_read = FALSE
`

func (q *Queries) CountUnreadMessagesForUser(ctx context.Context, parentID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadMessagesForUser, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, sender_id, content, is_read, sent_at
`

type CreateMessageParams struct {
	ConversationID uuid.UUID
	SenderID       uuid.UUID
	Content        string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.ConversationID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.IsRead,
		&i.SentAt,
	)
	return i, err
}

const getMessageCountByUserPair = `-- name: GetMessageCountByUserPair :one
SELECT COUNT(*) FROM messages m
JOIN conversations c ON c.id = m.conversation_id
WHERE c.parent_id = $1 AND c.babysitter_id = $2
  AND m.sent_at >= NOW() - INTERVAL '30 days'
`

type GetMessageCountByUserPairParams struct {
	ParentID     uuid.UUID
	BabysitterID uuid.UUID
}

func (q *Queries) GetMessageCountByUserPair(ctx context.Context, arg GetMessageCountByUserPairParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMessageCountByUserPair, arg.ParentID, arg.BabysitterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserMessageCount = `-- name: GetUserMessageCount :one
SELECT COUNT(*) FROM messages m
JOIN conversations c ON c.id = m.conversation_id
WHERE (c.parent_id = $1 OR c.babysitter_id = $1)
  AND m.sent_at >= NOW() - INTERVAL '30 days'
`

func (q *Queries) GetUserMessageCount(ctx context.Context, parentID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserMessageCount, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT id, conversation_id, sender_id, content, is_read, sent_at FROM messages
WHERE conversation_id = $1
ORDER BY sent_at ASC
`

func (q *Queries) ListMessagesByConversation(ctx context.Context, conversationID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.IsRead,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessagesAsRead = `-- name: MarkMessagesAsRead :exec
UPDATE messages
SET is_read = TRUE
WHERE conversation_id = $1
  AND sender_id != $2
  AND is_read = FALSE
`

type MarkMessagesAsReadParams struct {
	ConversationID uuid.UUID
	SenderID       uuid.UUID
}

func (q *Queries) MarkMessagesAsRead(ctx context.Context, arg MarkMessagesAsReadParams) error {
	_, err := q.db.ExecContext(ctx, markMessagesAsRead, arg.ConversationID, arg.SenderID)
	return err
}

const getLastMessagePerConversation = `-- name: GetLastMessagePerConversation :many
SELECT DISTINCT ON (m.conversation_id)
    m.id,
    m.conversation_id,
    m.sender_id,
    m.content,
    m.is_read,
    m.sent_at
FROM messages m
JOIN conversations c ON c.id = m.conversation_id
WHERE c.parent_id = $1 OR c.babysitter_id = $1
ORDER BY m.conversation_id, m.sent_at DESC
`

func (q *Queries) GetLastMessagePerConversation(ctx context.Context, userID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getLastMessagePerConversation, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.IsRead,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
