// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type RateType string

const (
	RateTypeHourly  RateType = "hourly"
	RateTypeDaily   RateType = "daily"
	RateTypeWeekly  RateType = "weekly"
	RateTypeMonthly RateType = "monthly"
)

func (e *RateType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RateType(s)
	case string:
		*e = RateType(s)
	default:
		return fmt.Errorf("unsupported scan type for RateType: %T", src)
	}
	return nil
}

type NullRateType struct {
	RateType RateType
	Valid    bool // Valid is true if RateType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRateType) Scan(value interface{}) error {
	if value == nil {
		ns.RateType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RateType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRateType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RateType), nil
}

type UserRole string

const (
	UserRoleAdmin      UserRole = "admin"
	UserRoleBabysitter UserRole = "babysitter"
	UserRoleParent     UserRole = "parent"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusDeleted   UserStatus = "deleted"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type BabysitterProfile struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Location          sql.NullString
	NationalIDUrl     sql.NullString
	LciLetterUrl      sql.NullString
	CvUrl             sql.NullString
	ProfilePictureUrl sql.NullString
	Languages         []string
	DaysPerWeek       sql.NullInt32
	HoursPerDay       sql.NullInt32
	RateType          NullRateType
	RateAmount        sql.NullString
	PaymentMethod     sql.NullString
	IsApproved        bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Gender            sql.NullString
	Availability      []string
	Currency          string
	IsAvailable       bool
}

type Conversation struct {
	ID              uuid.UUID
	ParentID        uuid.UUID
	BabysitterID    uuid.UUID
	StreamChannelID sql.NullString
	IsLocked        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Message struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	SenderID       uuid.UUID
	Content        string
	IsRead         bool
	SentAt         time.Time
}

type ParentProfile struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Location        sql.NullString
	Occupation      sql.NullString
	PreferredHours  sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
	PrimaryLocation sql.NullString
}

type ProfileView struct {
	ID           uuid.UUID
	BabysitterID uuid.UUID
	ParentID     uuid.UUID
	ViewedAt     time.Time
}

type SavedBabysitter struct {
	ID           uuid.UUID
	ParentID     uuid.UUID
	BabysitterID uuid.UUID
	SavedAt      time.Time
}

type User struct {
	ID           uuid.UUID
	FullName     string
	Email        string
	Phone        sql.NullString
	Role         UserRole
	Status       UserStatus
	ClerkUserID  sql.NullString
	PasswordHash sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}
