// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: parent_profiles.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createParentProfile = `-- name: CreateParentProfile :one
INSERT INTO parent_profiles (user_id, location, occupation, preferred_hours, primary_location)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, location, occupation, preferred_hours, created_at, updated_at, primary_location, profile_picture_url
`

type CreateParentProfileParams struct {
	UserID          uuid.UUID
	Location        sql.NullString
	Occupation      sql.NullString
	PreferredHours  sql.NullString
	PrimaryLocation sql.NullString
}

func (q *Queries) CreateParentProfile(ctx context.Context, arg CreateParentProfileParams) (ParentProfile, error) {
	row := q.db.QueryRowContext(ctx, createParentProfile,
		arg.UserID,
		arg.Location,
		arg.Occupation,
		arg.PreferredHours,
		arg.PrimaryLocation,
	)
	var i ParentProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Location,
		&i.Occupation,
		&i.PreferredHours,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrimaryLocation,
		&i.ProfilePictureUrl,
	)
	return i, err
}

const getParentProfileByUserID = `-- name: GetParentProfileByUserID :one
SELECT id, user_id, location, occupation, preferred_hours, created_at, updated_at, primary_location, profile_picture_url
FROM parent_profiles
WHERE user_id = $1
`

func (q *Queries) GetParentProfileByUserID(ctx context.Context, userID uuid.UUID) (ParentProfile, error) {
	row := q.db.QueryRowContext(ctx, getParentProfileByUserID, userID)
	var i ParentProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Location,
		&i.Occupation,
		&i.PreferredHours,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrimaryLocation,
		&i.ProfilePictureUrl,
	)
	return i, err
}

const updateParentProfile = `-- name: UpdateParentProfile :one
UPDATE parent_profiles
SET location = $2, occupation = $3, preferred_hours = $4, primary_location = $5, profile_picture_url = $6, updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, location, occupation, preferred_hours, created_at, updated_at, primary_location, profile_picture_url
`

type UpdateParentProfileParams struct {
	UserID            uuid.UUID
	Location          sql.NullString
	Occupation        sql.NullString
	PreferredHours    sql.NullString
	PrimaryLocation   sql.NullString
	ProfilePictureUrl sql.NullString
}

func (q *Queries) UpdateParentProfile(ctx context.Context, arg UpdateParentProfileParams) (ParentProfile, error) {
	row := q.db.QueryRowContext(ctx, updateParentProfile,
		arg.UserID,
		arg.Location,
		arg.Occupation,
		arg.PreferredHours,
		arg.PrimaryLocation,
		arg.ProfilePictureUrl,
	)
	var i ParentProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Location,
		&i.Occupation,
		&i.PreferredHours,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrimaryLocation,
		&i.ProfilePictureUrl,
	)
	return i, err
}
