// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: profile_views.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getWeeklyViewCount = `-- name: GetWeeklyViewCount :one
SELECT COUNT(*) FROM profile_views
WHERE babysitter_id = $1
  AND viewed_at >= NOW() - INTERVAL '7 days'
`

func (q *Queries) GetWeeklyViewCount(ctx context.Context, babysitterID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getWeeklyViewCount, babysitterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listProfileViewsForBabysitter = `-- name: ListProfileViewsForBabysitter :many
SELECT
    pv.id,
    pv.parent_id,
    u.full_name AS parent_name,
    u.email,
    u.phone,
    pp.occupation,
    pp.primary_location,
    pp.preferred_hours,
    pv.viewed_at,
    EXISTS (
        SELECT 1 FROM conversations c
        JOIN messages m ON m.conversation_id = c.id
        WHERE c.parent_id = pv.parent_id
          AND c.babysitter_id = $1
    ) AS has_messaged
FROM profile_views pv
JOIN users u ON u.id = pv.parent_id
LEFT JOIN parent_profiles pp ON pp.user_id = pv.parent_id
WHERE pv.babysitter_id = $1
ORDER BY pv.viewed_at DESC
`

type ListProfileViewsForBabysitterRow struct {
	ID              uuid.UUID
	ParentID        uuid.UUID
	ParentName      string
	Email           string
	Phone           sql.NullString
	Occupation      sql.NullString
	PrimaryLocation sql.NullString
	PreferredHours  sql.NullString
	ViewedAt        time.Time
	HasMessaged     bool
}

func (q *Queries) ListProfileViewsForBabysitter(ctx context.Context, babysitterID uuid.UUID) ([]ListProfileViewsForBabysitterRow, error) {
	rows, err := q.db.QueryContext(ctx, listProfileViewsForBabysitter, babysitterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProfileViewsForBabysitterRow
	for rows.Next() {
		var i ListProfileViewsForBabysitterRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.ParentName,
			&i.Email,
			&i.Phone,
			&i.Occupation,
			&i.PrimaryLocation,
			&i.PreferredHours,
			&i.ViewedAt,
			&i.HasMessaged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordProfileView = `-- name: RecordProfileView :one
INSERT INTO profile_views (babysitter_id, parent_id)
VALUES ($1, $2)
RETURNING id, babysitter_id, parent_id, viewed_at
`

type RecordProfileViewParams struct {
	BabysitterID uuid.UUID
	ParentID     uuid.UUID
}

func (q *Queries) RecordProfileView(ctx context.Context, arg RecordProfileViewParams) (ProfileView, error) {
	row := q.db.QueryRowContext(ctx, recordProfileView, arg.BabysitterID, arg.ParentID)
	var i ProfileView
	err := row.Scan(
		&i.ID,
		&i.BabysitterID,
		&i.ParentID,
		&i.ViewedAt,
	)
	return i, err
}
