// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: profile_views.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listProfileViewsForBabysitter = `-- name: ListProfileViewsForBabysitter :many
SELECT pv.id, pv.parent_id, u.full_name AS parent_name, pv.viewed_at
FROM profile_views pv
JOIN users u ON u.id = pv.parent_id
WHERE pv.babysitter_id = $1
ORDER BY pv.viewed_at DESC
`

type ListProfileViewsForBabysitterRow struct {
	ID         uuid.UUID
	ParentID   uuid.UUID
	ParentName string
	ViewedAt   time.Time
}

func (q *Queries) ListProfileViewsForBabysitter(ctx context.Context, babysitterID uuid.UUID) ([]ListProfileViewsForBabysitterRow, error) {
	rows, err := q.db.QueryContext(ctx, listProfileViewsForBabysitter, babysitterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProfileViewsForBabysitterRow
	for rows.Next() {
		var i ListProfileViewsForBabysitterRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.ParentName,
			&i.ViewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordProfileView = `-- name: RecordProfileView :one
INSERT INTO profile_views (babysitter_id, parent_id)
VALUES ($1, $2)
RETURNING id, babysitter_id, parent_id, viewed_at
`

type RecordProfileViewParams struct {
	BabysitterID uuid.UUID
	ParentID     uuid.UUID
}

func (q *Queries) RecordProfileView(ctx context.Context, arg RecordProfileViewParams) (ProfileView, error) {
	row := q.db.QueryRowContext(ctx, recordProfileView, arg.BabysitterID, arg.ParentID)
	var i ProfileView
	err := row.Scan(
		&i.ID,
		&i.BabysitterID,
		&i.ParentID,
		&i.ViewedAt,
	)
	return i, err
}
