// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reports.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (reporter_id, reported_user_id, report_type, description)
VALUES ($1, $2, $3, $4)
RETURNING id, reporter_id, reported_user_id, report_type, description, status, created_at, updated_at
`

type CreateReportParams struct {
	ReporterID     uuid.UUID
	ReportedUserID uuid.UUID
	ReportType     string
	Description    sql.NullString
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, createReport,
		arg.ReporterID,
		arg.ReportedUserID,
		arg.ReportType,
		arg.Description,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ReportedUserID,
		&i.ReportType,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT
    r.id, r.reporter_id, r.reported_user_id, r.report_type, r.description, r.status, r.created_at, r.updated_at,
    reporter.full_name   AS reporter_name,
    reporter.email       AS reporter_email,
    reported.full_name   AS reported_name,
    reported.email       AS reported_email
FROM reports r
JOIN users reporter ON reporter.id = r.reporter_id
JOIN users reported ON reported.id = r.reported_user_id
WHERE r.id = $1
`

type GetReportRow struct {
	ID             uuid.UUID
	ReporterID     uuid.UUID
	ReportedUserID uuid.UUID
	ReportType     string
	Description    sql.NullString
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ReporterName   string
	ReporterEmail  string
	ReportedName   string
	ReportedEmail  string
}

func (q *Queries) GetReport(ctx context.Context, id uuid.UUID) (GetReportRow, error) {
	row := q.db.QueryRowContext(ctx, getReport, id)
	var i GetReportRow
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ReportedUserID,
		&i.ReportType,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReporterName,
		&i.ReporterEmail,
		&i.ReportedName,
		&i.ReportedEmail,
	)
	return i, err
}

const listReports = `-- name: ListReports :many
SELECT
    r.id, r.reporter_id, r.reported_user_id, r.report_type, r.description, r.status, r.created_at, r.updated_at,
    reporter.full_name   AS reporter_name,
    reporter.email       AS reporter_email,
    reported.full_name   AS reported_name,
    reported.email       AS reported_email
FROM reports r
JOIN users reporter ON reporter.id = r.reporter_id
JOIN users reported ON reported.id = r.reported_user_id
ORDER BY r.created_at DESC
`

type ListReportsRow struct {
	ID             uuid.UUID
	ReporterID     uuid.UUID
	ReportedUserID uuid.UUID
	ReportType     string
	Description    sql.NullString
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ReporterName   string
	ReporterEmail  string
	ReportedName   string
	ReportedEmail  string
}

func (q *Queries) ListReports(ctx context.Context) ([]ListReportsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportsRow
	for rows.Next() {
		var i ListReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ReportedUserID,
			&i.ReportType,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReporterName,
			&i.ReporterEmail,
			&i.ReportedName,
			&i.ReportedEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByStatus = `-- name: ListReportsByStatus :many
SELECT
    r.id, r.reporter_id, r.reported_user_id, r.report_type, r.description, r.status, r.created_at, r.updated_at,
    reporter.full_name   AS reporter_name,
    reporter.email       AS reporter_email,
    reported.full_name   AS reported_name,
    reported.email       AS reported_email
FROM reports r
JOIN users reporter ON reporter.id = r.reporter_id
JOIN users reported ON reported.id = r.reported_user_id
WHERE r.status = $1
ORDER BY r.created_at DESC
`

type ListReportsByStatusRow struct {
	ID             uuid.UUID
	ReporterID     uuid.UUID
	ReportedUserID uuid.UUID
	ReportType     string
	Description    sql.NullString
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ReporterName   string
	ReporterEmail  string
	ReportedName   string
	ReportedEmail  string
}

func (q *Queries) ListReportsByStatus(ctx context.Context, status string) ([]ListReportsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listReportsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportsByStatusRow
	for rows.Next() {
		var i ListReportsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ReportedUserID,
			&i.ReportType,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReporterName,
			&i.ReporterEmail,
			&i.ReportedName,
			&i.ReportedEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportStatus = `-- name: UpdateReportStatus :one
UPDATE reports
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, reporter_id, reported_user_id, report_type, description, status, created_at, updated_at
`

type UpdateReportStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, updateReportStatus, arg.ID, arg.Status)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ReportedUserID,
		&i.ReportType,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
