// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: saved_babysitters.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const listSavedBabysitters = `-- name: ListSavedBabysitters :many
SELECT u.id, u.full_name, u.email, u.phone, u.status,
       bp.location, bp.profile_picture_url, bp.languages,
       bp.days_per_week, bp.hours_per_day, bp.rate_type,
       bp.rate_amount, bp.payment_method, bp.is_approved,
       bp.gender, bp.availability, bp.currency, bp.is_available
FROM saved_babysitters sb
JOIN users u ON u.id = sb.babysitter_id
JOIN babysitter_profiles bp ON u.id = bp.user_id
WHERE sb.parent_id = $1
  AND u.deleted_at IS NULL
  AND u.status = 'active'
ORDER BY sb.saved_at DESC
`

type ListSavedBabysittersRow struct {
	ID                uuid.UUID
	FullName          string
	Email             string
	Phone             sql.NullString
	Status            UserStatus
	Location          sql.NullString
	ProfilePictureUrl sql.NullString
	Languages         []string
	DaysPerWeek       sql.NullInt32
	HoursPerDay       sql.NullInt32
	RateType          NullRateType
	RateAmount        sql.NullString
	PaymentMethod     sql.NullString
	IsApproved        bool
	Gender            sql.NullString
	Availability      []string
	Currency          string
	IsAvailable       bool
}

func (q *Queries) ListSavedBabysitters(ctx context.Context, parentID uuid.UUID) ([]ListSavedBabysittersRow, error) {
	rows, err := q.db.QueryContext(ctx, listSavedBabysitters, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSavedBabysittersRow
	for rows.Next() {
		var i ListSavedBabysittersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.Status,
			&i.Location,
			&i.ProfilePictureUrl,
			pq.Array(&i.Languages),
			&i.DaysPerWeek,
			&i.HoursPerDay,
			&i.RateType,
			&i.RateAmount,
			&i.PaymentMethod,
			&i.IsApproved,
			&i.Gender,
			pq.Array(&i.Availability),
			&i.Currency,
			&i.IsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveBabysitter = `-- name: SaveBabysitter :exec
INSERT INTO saved_babysitters (parent_id, babysitter_id)
VALUES ($1, $2)
ON CONFLICT (parent_id, babysitter_id) DO NOTHING
`

type SaveBabysitterParams struct {
	ParentID     uuid.UUID
	BabysitterID uuid.UUID
}

func (q *Queries) SaveBabysitter(ctx context.Context, arg SaveBabysitterParams) error {
	_, err := q.db.ExecContext(ctx, saveBabysitter, arg.ParentID, arg.BabysitterID)
	return err
}

const unsaveBabysitter = `-- name: UnsaveBabysitter :exec
DELETE FROM saved_babysitters
WHERE parent_id = $1 AND babysitter_id = $2
`

type UnsaveBabysitterParams struct {
	ParentID     uuid.UUID
	BabysitterID uuid.UUID
}

func (q *Queries) UnsaveBabysitter(ctx context.Context, arg UnsaveBabysitterParams) error {
	_, err := q.db.ExecContext(ctx, unsaveBabysitter, arg.ParentID, arg.BabysitterID)
	return err
}
